// Code generated by Kitex v0.15.2. DO NOT EDIT.

package userservice

import (
	"context"
	user "github.com/ant-02/myreel-plus/kitex_gen/user"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Login(ctx context.Context, Req *user.LoginRequest, callOptions ...callopt.Option) (r *user.LoginResponse, err error)
	Register(ctx context.Context, Req *user.RegisterRequest, callOptions ...callopt.Option) (r *user.RegisterResponse, err error)
	GetUserInfo(ctx context.Context, Req *user.GetUserInfoRequest, callOptions ...callopt.Option) (r *user.GetUserInfoResponse, err error)
	GetUploadToken(ctx context.Context, Req *user.GetUploadTokenRequest, callOptions ...callopt.Option) (r *user.GetUploadTokenResponse, err error)
	GetMFA(ctx context.Context, Req *user.GetMFARequest, callOptions ...callopt.Option) (r *user.GetMFAResponse, err error)
	BindMFA(ctx context.Context, Req *user.BindMFARequest, callOptions ...callopt.Option) (r *user.BindMFAResponse, err error)
	SearchImg(ctx context.Context, Req *user.SearchImgRequest, callOptions ...callopt.Option) (r *user.SearchImgResponse, err error)
	Refresh(ctx context.Context, Req *user.RefreshRequest, callOptions ...callopt.Option) (r *user.RefreshResponse, err error)
	SetUserAvatarUrl(ctx context.Context, Req *user.SetUserAvatarUrlRequest, callOptions ...callopt.Option) (r *user.SetUserAvatarUrlResponse, err error)
	GetUseridByUsername(ctx context.Context, Req *user.GetUserIdByUsernameRequest, callOptions ...callopt.Option) (r *user.GetUserIdByUsernameResponse, err error)
	GetUsersByIds(ctx context.Context, Req *user.GetUsersByIdsRequest, callOptions ...callopt.Option) (r *user.GetUsersByIdsResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Login(ctx context.Context, Req *user.LoginRequest, callOptions ...callopt.Option) (r *user.LoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, Req)
}

func (p *kUserServiceClient) Register(ctx context.Context, Req *user.RegisterRequest, callOptions ...callopt.Option) (r *user.RegisterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, Req)
}

func (p *kUserServiceClient) GetUserInfo(ctx context.Context, Req *user.GetUserInfoRequest, callOptions ...callopt.Option) (r *user.GetUserInfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserInfo(ctx, Req)
}

func (p *kUserServiceClient) GetUploadToken(ctx context.Context, Req *user.GetUploadTokenRequest, callOptions ...callopt.Option) (r *user.GetUploadTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUploadToken(ctx, Req)
}

func (p *kUserServiceClient) GetMFA(ctx context.Context, Req *user.GetMFARequest, callOptions ...callopt.Option) (r *user.GetMFAResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMFA(ctx, Req)
}

func (p *kUserServiceClient) BindMFA(ctx context.Context, Req *user.BindMFARequest, callOptions ...callopt.Option) (r *user.BindMFAResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BindMFA(ctx, Req)
}

func (p *kUserServiceClient) SearchImg(ctx context.Context, Req *user.SearchImgRequest, callOptions ...callopt.Option) (r *user.SearchImgResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchImg(ctx, Req)
}

func (p *kUserServiceClient) Refresh(ctx context.Context, Req *user.RefreshRequest, callOptions ...callopt.Option) (r *user.RefreshResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Refresh(ctx, Req)
}

func (p *kUserServiceClient) SetUserAvatarUrl(ctx context.Context, Req *user.SetUserAvatarUrlRequest, callOptions ...callopt.Option) (r *user.SetUserAvatarUrlResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetUserAvatarUrl(ctx, Req)
}

func (p *kUserServiceClient) GetUseridByUsername(ctx context.Context, Req *user.GetUserIdByUsernameRequest, callOptions ...callopt.Option) (r *user.GetUserIdByUsernameResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUseridByUsername(ctx, Req)
}

func (p *kUserServiceClient) GetUsersByIds(ctx context.Context, Req *user.GetUsersByIdsRequest, callOptions ...callopt.Option) (r *user.GetUsersByIdsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUsersByIds(ctx, Req)
}
