// Code generated by Kitex v0.15.2. DO NOT EDIT.

package userservice

import (
	"context"
	"errors"
	user "github.com/ant-02/myreel-plus/kitex_gen/user"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newLoginArgs,
		newLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newRegisterArgs,
		newRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetUserInfo": kitex.NewMethodInfo(
		getUserInfoHandler,
		newGetUserInfoArgs,
		newGetUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetUploadToken": kitex.NewMethodInfo(
		getUploadTokenHandler,
		newGetUploadTokenArgs,
		newGetUploadTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetMFA": kitex.NewMethodInfo(
		getMFAHandler,
		newGetMFAArgs,
		newGetMFAResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"BindMFA": kitex.NewMethodInfo(
		bindMFAHandler,
		newBindMFAArgs,
		newBindMFAResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SearchImg": kitex.NewMethodInfo(
		searchImgHandler,
		newSearchImgArgs,
		newSearchImgResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Refresh": kitex.NewMethodInfo(
		refreshHandler,
		newRefreshArgs,
		newRefreshResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SetUserAvatarUrl": kitex.NewMethodInfo(
		setUserAvatarUrlHandler,
		newSetUserAvatarUrlArgs,
		newSetUserAvatarUrlResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetUseridByUsername": kitex.NewMethodInfo(
		getUseridByUsernameHandler,
		newGetUseridByUsernameArgs,
		newGetUseridByUsernameResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetUsersByIds": kitex.NewMethodInfo(
		getUsersByIdsHandler,
		newGetUsersByIdsArgs,
		newGetUsersByIdsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.LoginRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).Login(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *LoginArgs:
		success, err := handler.(user.UserService).Login(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*LoginResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newLoginArgs() interface{} {
	return &LoginArgs{}
}

func newLoginResult() interface{} {
	return &LoginResult{}
}

type LoginArgs struct {
	Req *user.LoginRequest
}

func (p *LoginArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *LoginArgs) Unmarshal(in []byte) error {
	msg := new(user.LoginRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var LoginArgs_Req_DEFAULT *user.LoginRequest

func (p *LoginArgs) GetReq() *user.LoginRequest {
	if !p.IsSetReq() {
		return LoginArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *LoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginArgs) GetFirstArgument() interface{} {
	return p.Req
}

type LoginResult struct {
	Success *user.LoginResponse
}

var LoginResult_Success_DEFAULT *user.LoginResponse

func (p *LoginResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *LoginResult) Unmarshal(in []byte) error {
	msg := new(user.LoginResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *LoginResult) GetSuccess() *user.LoginResponse {
	if !p.IsSetSuccess() {
		return LoginResult_Success_DEFAULT
	}
	return p.Success
}

func (p *LoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.LoginResponse)
}

func (p *LoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginResult) GetResult() interface{} {
	return p.Success
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.RegisterRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).Register(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RegisterArgs:
		success, err := handler.(user.UserService).Register(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RegisterResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRegisterArgs() interface{} {
	return &RegisterArgs{}
}

func newRegisterResult() interface{} {
	return &RegisterResult{}
}

type RegisterArgs struct {
	Req *user.RegisterRequest
}

func (p *RegisterArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RegisterArgs) Unmarshal(in []byte) error {
	msg := new(user.RegisterRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RegisterArgs_Req_DEFAULT *user.RegisterRequest

func (p *RegisterArgs) GetReq() *user.RegisterRequest {
	if !p.IsSetReq() {
		return RegisterArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RegisterArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RegisterResult struct {
	Success *user.RegisterResponse
}

var RegisterResult_Success_DEFAULT *user.RegisterResponse

func (p *RegisterResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RegisterResult) Unmarshal(in []byte) error {
	msg := new(user.RegisterResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RegisterResult) GetSuccess() *user.RegisterResponse {
	if !p.IsSetSuccess() {
		return RegisterResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.RegisterResponse)
}

func (p *RegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RegisterResult) GetResult() interface{} {
	return p.Success
}

func getUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.GetUserInfoRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).GetUserInfo(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetUserInfoArgs:
		success, err := handler.(user.UserService).GetUserInfo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUserInfoResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetUserInfoArgs() interface{} {
	return &GetUserInfoArgs{}
}

func newGetUserInfoResult() interface{} {
	return &GetUserInfoResult{}
}

type GetUserInfoArgs struct {
	Req *user.GetUserInfoRequest
}

func (p *GetUserInfoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetUserInfoArgs) Unmarshal(in []byte) error {
	msg := new(user.GetUserInfoRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUserInfoArgs_Req_DEFAULT *user.GetUserInfoRequest

func (p *GetUserInfoArgs) GetReq() *user.GetUserInfoRequest {
	if !p.IsSetReq() {
		return GetUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetUserInfoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetUserInfoResult struct {
	Success *user.GetUserInfoResponse
}

var GetUserInfoResult_Success_DEFAULT *user.GetUserInfoResponse

func (p *GetUserInfoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetUserInfoResult) Unmarshal(in []byte) error {
	msg := new(user.GetUserInfoResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUserInfoResult) GetSuccess() *user.GetUserInfoResponse {
	if !p.IsSetSuccess() {
		return GetUserInfoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.GetUserInfoResponse)
}

func (p *GetUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetUserInfoResult) GetResult() interface{} {
	return p.Success
}

func getUploadTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.GetUploadTokenRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).GetUploadToken(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetUploadTokenArgs:
		success, err := handler.(user.UserService).GetUploadToken(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUploadTokenResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetUploadTokenArgs() interface{} {
	return &GetUploadTokenArgs{}
}

func newGetUploadTokenResult() interface{} {
	return &GetUploadTokenResult{}
}

type GetUploadTokenArgs struct {
	Req *user.GetUploadTokenRequest
}

func (p *GetUploadTokenArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetUploadTokenArgs) Unmarshal(in []byte) error {
	msg := new(user.GetUploadTokenRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUploadTokenArgs_Req_DEFAULT *user.GetUploadTokenRequest

func (p *GetUploadTokenArgs) GetReq() *user.GetUploadTokenRequest {
	if !p.IsSetReq() {
		return GetUploadTokenArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUploadTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetUploadTokenArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetUploadTokenResult struct {
	Success *user.GetUploadTokenResponse
}

var GetUploadTokenResult_Success_DEFAULT *user.GetUploadTokenResponse

func (p *GetUploadTokenResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetUploadTokenResult) Unmarshal(in []byte) error {
	msg := new(user.GetUploadTokenResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUploadTokenResult) GetSuccess() *user.GetUploadTokenResponse {
	if !p.IsSetSuccess() {
		return GetUploadTokenResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUploadTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.GetUploadTokenResponse)
}

func (p *GetUploadTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetUploadTokenResult) GetResult() interface{} {
	return p.Success
}

func getMFAHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.GetMFARequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).GetMFA(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetMFAArgs:
		success, err := handler.(user.UserService).GetMFA(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetMFAResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetMFAArgs() interface{} {
	return &GetMFAArgs{}
}

func newGetMFAResult() interface{} {
	return &GetMFAResult{}
}

type GetMFAArgs struct {
	Req *user.GetMFARequest
}

func (p *GetMFAArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetMFAArgs) Unmarshal(in []byte) error {
	msg := new(user.GetMFARequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetMFAArgs_Req_DEFAULT *user.GetMFARequest

func (p *GetMFAArgs) GetReq() *user.GetMFARequest {
	if !p.IsSetReq() {
		return GetMFAArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetMFAArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetMFAArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetMFAResult struct {
	Success *user.GetMFAResponse
}

var GetMFAResult_Success_DEFAULT *user.GetMFAResponse

func (p *GetMFAResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetMFAResult) Unmarshal(in []byte) error {
	msg := new(user.GetMFAResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetMFAResult) GetSuccess() *user.GetMFAResponse {
	if !p.IsSetSuccess() {
		return GetMFAResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetMFAResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.GetMFAResponse)
}

func (p *GetMFAResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetMFAResult) GetResult() interface{} {
	return p.Success
}

func bindMFAHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.BindMFARequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).BindMFA(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *BindMFAArgs:
		success, err := handler.(user.UserService).BindMFA(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*BindMFAResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newBindMFAArgs() interface{} {
	return &BindMFAArgs{}
}

func newBindMFAResult() interface{} {
	return &BindMFAResult{}
}

type BindMFAArgs struct {
	Req *user.BindMFARequest
}

func (p *BindMFAArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *BindMFAArgs) Unmarshal(in []byte) error {
	msg := new(user.BindMFARequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BindMFAArgs_Req_DEFAULT *user.BindMFARequest

func (p *BindMFAArgs) GetReq() *user.BindMFARequest {
	if !p.IsSetReq() {
		return BindMFAArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BindMFAArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BindMFAArgs) GetFirstArgument() interface{} {
	return p.Req
}

type BindMFAResult struct {
	Success *user.BindMFAResponse
}

var BindMFAResult_Success_DEFAULT *user.BindMFAResponse

func (p *BindMFAResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *BindMFAResult) Unmarshal(in []byte) error {
	msg := new(user.BindMFAResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BindMFAResult) GetSuccess() *user.BindMFAResponse {
	if !p.IsSetSuccess() {
		return BindMFAResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BindMFAResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.BindMFAResponse)
}

func (p *BindMFAResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BindMFAResult) GetResult() interface{} {
	return p.Success
}

func searchImgHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.SearchImgRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).SearchImg(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SearchImgArgs:
		success, err := handler.(user.UserService).SearchImg(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SearchImgResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSearchImgArgs() interface{} {
	return &SearchImgArgs{}
}

func newSearchImgResult() interface{} {
	return &SearchImgResult{}
}

type SearchImgArgs struct {
	Req *user.SearchImgRequest
}

func (p *SearchImgArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SearchImgArgs) Unmarshal(in []byte) error {
	msg := new(user.SearchImgRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SearchImgArgs_Req_DEFAULT *user.SearchImgRequest

func (p *SearchImgArgs) GetReq() *user.SearchImgRequest {
	if !p.IsSetReq() {
		return SearchImgArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SearchImgArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SearchImgArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SearchImgResult struct {
	Success *user.SearchImgResponse
}

var SearchImgResult_Success_DEFAULT *user.SearchImgResponse

func (p *SearchImgResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SearchImgResult) Unmarshal(in []byte) error {
	msg := new(user.SearchImgResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SearchImgResult) GetSuccess() *user.SearchImgResponse {
	if !p.IsSetSuccess() {
		return SearchImgResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SearchImgResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.SearchImgResponse)
}

func (p *SearchImgResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchImgResult) GetResult() interface{} {
	return p.Success
}

func refreshHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.RefreshRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).Refresh(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RefreshArgs:
		success, err := handler.(user.UserService).Refresh(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RefreshResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRefreshArgs() interface{} {
	return &RefreshArgs{}
}

func newRefreshResult() interface{} {
	return &RefreshResult{}
}

type RefreshArgs struct {
	Req *user.RefreshRequest
}

func (p *RefreshArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RefreshArgs) Unmarshal(in []byte) error {
	msg := new(user.RefreshRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RefreshArgs_Req_DEFAULT *user.RefreshRequest

func (p *RefreshArgs) GetReq() *user.RefreshRequest {
	if !p.IsSetReq() {
		return RefreshArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RefreshArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RefreshArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RefreshResult struct {
	Success *user.RefreshResponse
}

var RefreshResult_Success_DEFAULT *user.RefreshResponse

func (p *RefreshResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RefreshResult) Unmarshal(in []byte) error {
	msg := new(user.RefreshResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RefreshResult) GetSuccess() *user.RefreshResponse {
	if !p.IsSetSuccess() {
		return RefreshResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RefreshResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.RefreshResponse)
}

func (p *RefreshResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RefreshResult) GetResult() interface{} {
	return p.Success
}

func setUserAvatarUrlHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.SetUserAvatarUrlRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).SetUserAvatarUrl(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SetUserAvatarUrlArgs:
		success, err := handler.(user.UserService).SetUserAvatarUrl(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SetUserAvatarUrlResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSetUserAvatarUrlArgs() interface{} {
	return &SetUserAvatarUrlArgs{}
}

func newSetUserAvatarUrlResult() interface{} {
	return &SetUserAvatarUrlResult{}
}

type SetUserAvatarUrlArgs struct {
	Req *user.SetUserAvatarUrlRequest
}

func (p *SetUserAvatarUrlArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SetUserAvatarUrlArgs) Unmarshal(in []byte) error {
	msg := new(user.SetUserAvatarUrlRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SetUserAvatarUrlArgs_Req_DEFAULT *user.SetUserAvatarUrlRequest

func (p *SetUserAvatarUrlArgs) GetReq() *user.SetUserAvatarUrlRequest {
	if !p.IsSetReq() {
		return SetUserAvatarUrlArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SetUserAvatarUrlArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SetUserAvatarUrlArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SetUserAvatarUrlResult struct {
	Success *user.SetUserAvatarUrlResponse
}

var SetUserAvatarUrlResult_Success_DEFAULT *user.SetUserAvatarUrlResponse

func (p *SetUserAvatarUrlResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SetUserAvatarUrlResult) Unmarshal(in []byte) error {
	msg := new(user.SetUserAvatarUrlResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SetUserAvatarUrlResult) GetSuccess() *user.SetUserAvatarUrlResponse {
	if !p.IsSetSuccess() {
		return SetUserAvatarUrlResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SetUserAvatarUrlResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.SetUserAvatarUrlResponse)
}

func (p *SetUserAvatarUrlResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SetUserAvatarUrlResult) GetResult() interface{} {
	return p.Success
}

func getUseridByUsernameHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.GetUserIdByUsernameRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).GetUseridByUsername(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetUseridByUsernameArgs:
		success, err := handler.(user.UserService).GetUseridByUsername(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUseridByUsernameResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetUseridByUsernameArgs() interface{} {
	return &GetUseridByUsernameArgs{}
}

func newGetUseridByUsernameResult() interface{} {
	return &GetUseridByUsernameResult{}
}

type GetUseridByUsernameArgs struct {
	Req *user.GetUserIdByUsernameRequest
}

func (p *GetUseridByUsernameArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetUseridByUsernameArgs) Unmarshal(in []byte) error {
	msg := new(user.GetUserIdByUsernameRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUseridByUsernameArgs_Req_DEFAULT *user.GetUserIdByUsernameRequest

func (p *GetUseridByUsernameArgs) GetReq() *user.GetUserIdByUsernameRequest {
	if !p.IsSetReq() {
		return GetUseridByUsernameArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUseridByUsernameArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetUseridByUsernameArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetUseridByUsernameResult struct {
	Success *user.GetUserIdByUsernameResponse
}

var GetUseridByUsernameResult_Success_DEFAULT *user.GetUserIdByUsernameResponse

func (p *GetUseridByUsernameResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetUseridByUsernameResult) Unmarshal(in []byte) error {
	msg := new(user.GetUserIdByUsernameResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUseridByUsernameResult) GetSuccess() *user.GetUserIdByUsernameResponse {
	if !p.IsSetSuccess() {
		return GetUseridByUsernameResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUseridByUsernameResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.GetUserIdByUsernameResponse)
}

func (p *GetUseridByUsernameResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetUseridByUsernameResult) GetResult() interface{} {
	return p.Success
}

func getUsersByIdsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.GetUsersByIdsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).GetUsersByIds(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetUsersByIdsArgs:
		success, err := handler.(user.UserService).GetUsersByIds(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUsersByIdsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetUsersByIdsArgs() interface{} {
	return &GetUsersByIdsArgs{}
}

func newGetUsersByIdsResult() interface{} {
	return &GetUsersByIdsResult{}
}

type GetUsersByIdsArgs struct {
	Req *user.GetUsersByIdsRequest
}

func (p *GetUsersByIdsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetUsersByIdsArgs) Unmarshal(in []byte) error {
	msg := new(user.GetUsersByIdsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUsersByIdsArgs_Req_DEFAULT *user.GetUsersByIdsRequest

func (p *GetUsersByIdsArgs) GetReq() *user.GetUsersByIdsRequest {
	if !p.IsSetReq() {
		return GetUsersByIdsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUsersByIdsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetUsersByIdsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetUsersByIdsResult struct {
	Success *user.GetUsersByIdsResponse
}

var GetUsersByIdsResult_Success_DEFAULT *user.GetUsersByIdsResponse

func (p *GetUsersByIdsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetUsersByIdsResult) Unmarshal(in []byte) error {
	msg := new(user.GetUsersByIdsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUsersByIdsResult) GetSuccess() *user.GetUsersByIdsResponse {
	if !p.IsSetSuccess() {
		return GetUsersByIdsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUsersByIdsResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.GetUsersByIdsResponse)
}

func (p *GetUsersByIdsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetUsersByIdsResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Login(ctx context.Context, Req *user.LoginRequest) (r *user.LoginResponse, err error) {
	var _args LoginArgs
	_args.Req = Req
	var _result LoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Register(ctx context.Context, Req *user.RegisterRequest) (r *user.RegisterResponse, err error) {
	var _args RegisterArgs
	_args.Req = Req
	var _result RegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserInfo(ctx context.Context, Req *user.GetUserInfoRequest) (r *user.GetUserInfoResponse, err error) {
	var _args GetUserInfoArgs
	_args.Req = Req
	var _result GetUserInfoResult
	if err = p.c.Call(ctx, "GetUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUploadToken(ctx context.Context, Req *user.GetUploadTokenRequest) (r *user.GetUploadTokenResponse, err error) {
	var _args GetUploadTokenArgs
	_args.Req = Req
	var _result GetUploadTokenResult
	if err = p.c.Call(ctx, "GetUploadToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetMFA(ctx context.Context, Req *user.GetMFARequest) (r *user.GetMFAResponse, err error) {
	var _args GetMFAArgs
	_args.Req = Req
	var _result GetMFAResult
	if err = p.c.Call(ctx, "GetMFA", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BindMFA(ctx context.Context, Req *user.BindMFARequest) (r *user.BindMFAResponse, err error) {
	var _args BindMFAArgs
	_args.Req = Req
	var _result BindMFAResult
	if err = p.c.Call(ctx, "BindMFA", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchImg(ctx context.Context, Req *user.SearchImgRequest) (r *user.SearchImgResponse, err error) {
	var _args SearchImgArgs
	_args.Req = Req
	var _result SearchImgResult
	if err = p.c.Call(ctx, "SearchImg", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Refresh(ctx context.Context, Req *user.RefreshRequest) (r *user.RefreshResponse, err error) {
	var _args RefreshArgs
	_args.Req = Req
	var _result RefreshResult
	if err = p.c.Call(ctx, "Refresh", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetUserAvatarUrl(ctx context.Context, Req *user.SetUserAvatarUrlRequest) (r *user.SetUserAvatarUrlResponse, err error) {
	var _args SetUserAvatarUrlArgs
	_args.Req = Req
	var _result SetUserAvatarUrlResult
	if err = p.c.Call(ctx, "SetUserAvatarUrl", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUseridByUsername(ctx context.Context, Req *user.GetUserIdByUsernameRequest) (r *user.GetUserIdByUsernameResponse, err error) {
	var _args GetUseridByUsernameArgs
	_args.Req = Req
	var _result GetUseridByUsernameResult
	if err = p.c.Call(ctx, "GetUseridByUsername", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUsersByIds(ctx context.Context, Req *user.GetUsersByIdsRequest) (r *user.GetUsersByIdsResponse, err error) {
	var _args GetUsersByIdsArgs
	_args.Req = Req
	var _result GetUsersByIdsResult
	if err = p.c.Call(ctx, "GetUsersByIds", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
