// Code generated by hertz generator.

package auth

import (
	"context"

	auth "github.com/ant-02/myreel-plus/internal/gateway/model/api/auth"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Login .
// @router /api/v1/auth/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req auth.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(auth.LoginResponse)

	c.JSON(consts.StatusOK, resp)
}
