// Code generated by Kitex v0.15.2. DO NOT EDIT.

package auth

import (
	"context"
	"github.com/ant-02/myreel-plus/kitex_gen/model"

	"github.com/cloudwego/prutal"
)

type User struct {
	Username  string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	AvatarUrl string `protobuf:"bytes,2,opt,name=avatar_url" json:"avatar_url,omitempty"`
}

func (x *User) Reset() { *x = User{} }

func (x *User) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *User) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type Token struct {
	AccessToken       string `protobuf:"bytes,1,opt,name=access_token" json:"access_token,omitempty"`
	AccessExpireTime  string `protobuf:"bytes,2,opt,name=access_expire_time" json:"access_expire_time,omitempty"`
	RefreshToken      string `protobuf:"bytes,3,opt,name=refresh_token" json:"refresh_token,omitempty"`
	RefreshExpireTime string `protobuf:"bytes,4,opt,name=refresh_expire_time" json:"refresh_expire_time,omitempty"`
}

func (x *Token) Reset() { *x = Token{} }

func (x *Token) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Token) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Token) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Token) GetAccessExpireTime() string {
	if x != nil {
		return x.AccessExpireTime
	}
	return ""
}

func (x *Token) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *Token) GetRefreshExpireTime() string {
	if x != nil {
		return x.RefreshExpireTime
	}
	return ""
}

type UserWithToken struct {
	User  *User  `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Token *Token `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (x *UserWithToken) Reset() { *x = UserWithToken{} }

func (x *UserWithToken) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserWithToken) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserWithToken) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserWithToken) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type LoginRequest struct {
	Identity     string `protobuf:"bytes,1,opt,name=identity" json:"identity,omitempty"`
	Password     string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	IdentityType int64  `protobuf:"varint,3,opt,name=identity_type" json:"identity_type,omitempty"`
}

func (x *LoginRequest) Reset() { *x = LoginRequest{} }

func (x *LoginRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LoginRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LoginRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetIdentityType() int64 {
	if x != nil {
		return x.IdentityType
	}
	return 0
}

type LoginResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
}

func (x *LoginResponse) Reset() { *x = LoginResponse{} }

func (x *LoginResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LoginResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LoginResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type LoginMFAVerifyRequest struct {
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
}

func (x *LoginMFAVerifyRequest) Reset() { *x = LoginMFAVerifyRequest{} }

func (x *LoginMFAVerifyRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *LoginMFAVerifyRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LoginMFAVerifyRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type LoginMFAVerifyResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
}

func (x *LoginMFAVerifyResponse) Reset() { *x = LoginMFAVerifyResponse{} }

func (x *LoginMFAVerifyResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *LoginMFAVerifyResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LoginMFAVerifyResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type RegisterRequest struct {
	Identity     string `protobuf:"bytes,1,opt,name=identity" json:"identity,omitempty"`
	IdentityType int64  `protobuf:"varint,2,opt,name=identity_type" json:"identity_type,omitempty"`
}

func (x *RegisterRequest) Reset() { *x = RegisterRequest{} }

func (x *RegisterRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RegisterRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RegisterRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *RegisterRequest) GetIdentityType() int64 {
	if x != nil {
		return x.IdentityType
	}
	return 0
}

type RegisterResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
}

func (x *RegisterResponse) Reset() { *x = RegisterResponse{} }

func (x *RegisterResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RegisterResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RegisterResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type RegisterMFAVerifyRequest struct {
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
}

func (x *RegisterMFAVerifyRequest) Reset() { *x = RegisterMFAVerifyRequest{} }

func (x *RegisterMFAVerifyRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *RegisterMFAVerifyRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RegisterMFAVerifyRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type RegisterMFAVerifyResponse struct {
	Base *model.BaseResp `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
}

func (x *RegisterMFAVerifyResponse) Reset() { *x = RegisterMFAVerifyResponse{} }

func (x *RegisterMFAVerifyResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *RegisterMFAVerifyResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RegisterMFAVerifyResponse) GetBase() *model.BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

type AuthService interface {
	Login(ctx context.Context, req *LoginRequest) (res *LoginResponse, err error)
}
