services:
  # mysql服务
  myreel-mysql:
    container_name: myreel-mysql
    image: mysql:9.0.1
    env_file:
      - "./env/mysql.env"
    ports:
      - "3306:3306"
    networks:
      - myreel
    volumes:
      - ../config/sql:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql

  # etcd服务
  myreel-etcd:
    container_name: myreel-etcd
    image: quay.io/coreos/etcd:v3.5.5
    restart: always
    ports:
      - 2379:2379
      - 2380:2380
    env_file:
      - "./env/etcd.env"
    volumes:
      - ./script:/script
      - ../config:/config
      - ./data/etcd:/etcd-data
    networks:
      - myreel
    entrypoint:
      [
        "sh",
        "-c",
        "chmod +x /script/etcd-monitor.sh && /script/etcd-monitor.sh & exec etcd",
      ]

networks:
  myreel:
    driver: bridge
    name: myreel
