// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	auth "github.com/ant-02/myreel-plus/internal/gateway/router/auth"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	auth.Register(r)
}
