// Code generated by hertz generator.

package main

import (
	"github.com/ant-02/myreel-plus/config"
	"github.com/ant-02/myreel-plus/internal/gateway/router"
	"github.com/ant-02/myreel-plus/pkg/util"
	"github.com/bytedance/gopkg/util/logger"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func init() {
	config.Init()
}

func main() {
	addr, err := util.GetAvailablePort()
	if err != nil {
		logger.Fatalf("User: get available port failed, err: %v", err)
	}

	h := server.New(
		server.WithHostPorts(addr),
	)

	router.GeneratedRegister(h)
	h.Spin()
}
