// Code generated by hertz generator.

package main

import (
	"github.com/ant-02/myreel-plus/config"
	"github.com/ant-02/myreel-plus/internal/gateway/router"
	"github.com/ant-02/myreel-plus/internal/gateway/rpc"
	"github.com/ant-02/myreel-plus/pkg/constants"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func init() {
	config.Init(constants.GatewayServiceName)
	rpc.Init()
}

func main() {
	h := server.Default()

	router.GeneratedRegister(h)
	h.Spin()
}
