syntax = "proto3";

package user;

option go_package = "/user";

import "model.proto";

message User {
  int64  id        = 1;
  string username  = 2;
  string password  = 3;
  string avatarUrl = 4;
  string createdAt = 5;
  string updatedAt = 6;
  string deletedAt = 7;
}

message UserProfile {
  int64  id        = 1;
  string username  = 2;
  string avatarUrl = 3;
}

message LoginRequest {
  string username = 1;
  string password = 2;
  string code     = 3;
}

message Token {
  string accessToken       = 1;
  int64  accessExpireTime  = 2;
  string refreshToken      = 3;
  int64  refreshExpireTime = 4;
}

message UserWithToken {
  User  user  = 1;
  Token token = 2;
}

message LoginResponse {
  model.BaseResp base = 1;
  UserWithToken  data = 2;
}

message RegisterRequest {
  string username = 1;
  string password = 2;
}

message RegisterResponse {
  model.BaseResp base = 1;
}

message GetUserInfoRequest {
  int64 userId = 1;
}

message GetUserInfoResponse {
  model.BaseResp base = 1;
  User           data = 2;
}

message GetUploadTokenRequest {
  string suffix = 1;
  int64  userId = 2;
}

message GetUploadTokenResponse {
  model.BaseResp   base = 1;
  model.UpyunToken data = 2;
}

message SetUserAvatarUrlRequest {
  int64  userId = 1;
  string url    = 2;
}

message SetUserAvatarUrlResponse {
  model.BaseResp base = 1;
}

message MFA {
  string secret = 1;
  string qrcode = 2;
}

message GetMFARequest {}

message GetMFAResponse {
  model.BaseResp base = 1;
  MFA            data = 2;
}

message BindMFARequest {
  string code   = 1;
  string secret = 2;
}

message BindMFAResponse {
  model.BaseResp base = 1;
}

message SearchImgRequest {
  string data = 1;
}

message SearchImgResponse {
  model.BaseResp base = 1;
  string         data = 2;
}

message RefreshRequest {
  string token  = 1;
  int64  userId = 2;
}

message RefreshResponse {
  model.BaseResp base  = 1;
  string         token = 2;
}

message GetUserIdByUsernameRequest {
  string username = 1;
}

message GetUserIdByUsernameResponse {
  model.BaseResp base   = 1;
  int64          userId = 2;
}

message GetUsersByIdsRequest {
  repeated int64 ids = 1;
}

message GetUsersByIdsResponse {
  model.BaseResp       base = 1;
  repeated UserProfile list = 2;
}

service UserService {
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc GetUserInfo(GetUserInfoRequest) returns (GetUserInfoResponse);
  rpc GetUploadToken(GetUploadTokenRequest) returns (GetUploadTokenResponse);
  rpc GetMFA(GetMFARequest) returns (GetMFAResponse);
  rpc BindMFA(BindMFARequest) returns (BindMFAResponse);
  rpc SearchImg(SearchImgRequest) returns (SearchImgResponse);
  rpc Refresh(RefreshRequest) returns (RefreshResponse);
  rpc SetUserAvatarUrl(SetUserAvatarUrlRequest) returns (SetUserAvatarUrlResponse);
  rpc GetUseridByUsername(GetUserIdByUsernameRequest) returns (GetUserIdByUsernameResponse);
  rpc GetUsersByIds(GetUsersByIdsRequest) returns (GetUsersByIdsResponse);
}