syntax = "proto3";

package user;

option go_package = "/api/user";

import "api.proto";

message User {
  int64  id        = 1;
  string username  = 2;
  string password  = 3;
  string avatarUrl = 4;
  string createdAt = 5;
  string updatedAt = 6;
  string deletedAt = 7;
}

message LoginRequest {
  string username = 1[(api.body)="username"];
  string password = 2[(api.body)="password"];
  string code     = 3[(api.body)="code"];
}

message Token {
  string accessToken       = 1;
  int64  accessExpireTime  = 2;
  string refreshToken      = 3;
  int64  refreshExpireTime = 4;
}

message LoginResponse {
  User  user  = 1;
  Token token = 2;
}

message RegisterRequest {
  string username = 1[(api.body)="username"];
  string password = 2[(api.body)="password"];
}

message RegisterResponse {}

message GetUserInfoRequest {}

message GetUserInfoResponse {
  User user = 1;
}

message AvatarNotifyRequest {
  string imageType   = 1[(api.body)="image-type"];
  int64  imageFrames = 2[(api.body)="image-frames"];
  int64  imageheight = 3[(api.body)="image-height"];
  int64  code        = 4[(api.body)="code"];
  int64  fileSize    = 5[(api.body)="file_size"];
  int64  imageWidth  = 6[(api.body)="image-width"];
  string url         = 7[(api.body)="url"];
  int64  time        = 8[(api.body)="time"];
  string message     = 9[(api.body)="message"];
  string minetype    = 10[(api.body)="minetype"];
  string uid         = 11[(api.body)="ext-param"];
}

message AvatarNotifyResponse {}

message GetUploadTokenRequest {
  string suffix = 1[(api.body)="suffix"];
}

message GetUploadTokenResponse {
  string policy        = 1;
  string authorization = 2;
  string bucket        = 3;
}

message MFA {
  string secret = 1;
  string qrcode = 2;
}

message GetMFARequest {}

message GetMFAResponse {
  MFA mfa = 1;
}

message BindMFARequest {
  string code   = 1[(api.body)="code"];
  string secret = 2[(api.body)="secret"];
}

message BindMFAResponse {}

message SearchImgRequest {
  string data = 1[(api.body)="data"];
}

message SearchImgResponse {
  string data = 1;
}

message RefreshRequest {}

message RefreshResponse {
  string token = 1;
}

service UserService {
  rpc Login(LoginRequest) returns (LoginResponse) {
    option (api.post)="/api/v1/user/login";
  }
  rpc Register(RegisterRequest) returns (RegisterResponse) {
    option (api.post)="/api/v1/user/register";
  }
  rpc GetUserInfo(GetUserInfoRequest) returns (GetUserInfoResponse) {
    option (api.get)="/api/v1/user/info";
  }
  rpc GetUploadToken(GetUploadTokenRequest) returns (GetUploadTokenResponse) {
    option (api.post)="/api/v1/user/avatar/token";
  }
  rpc GetMFA(GetMFARequest) returns (GetMFAResponse) {
    option (api.get)="/api/v1/user/mfa/qrcode";
  }
  rpc BindMFA(BindMFARequest) returns (BindMFAResponse) {
    option (api.post)="/api/v1/user/mfa/bind";
  }
  rpc SearchImg(SearchImgRequest) returns (SearchImgResponse) {
    option (api.post)="/api/v1/user/image/search";
  }
  rpc Refresh(RefreshRequest) returns (RefreshResponse) {
    option (api.get)="/api/v1/refresh";
  }
  rpc AvatarNotify(AvatarNotifyRequest) returns (AvatarNotifyResponse) {
    option (api.post)="/api/v1/user/avatar/notify";
  }
}